const events = {
  release: {id:'example_0042',type:'release.published',title:'Atlas Parser adds a local extraction mode.',summary:'A fictional project announces a release that could be relevant to document ingestion workflows.',evidence:['Release notes','Repository tag'],next:'Research agent: compare the new mode with the existing ingestion approach.',agents:['research','impact']},
  research: {id:'example_0043',type:'research.published',title:'A new method links extracted claims to source passages.',summary:'A fictional research update describes a way to keep evidence attached to an extracted claim.',evidence:['Research abstract','Method description'],next:'Connections agent: relate the method to verification work; Project Scout: assess a small evaluation project.',agents:['connections','project_scout']}
};
let selected='release';
function renderEvent(){const e=events[selected];document.getElementById('demo-id').textContent=e.id+' / '+e.type;document.getElementById('demo-title').textContent=e.title;document.getElementById('demo-description').textContent=e.summary;document.getElementById('demo-evidence').textContent=e.evidence.join(' + ');document.getElementById('demo-next').textContent=e.next;document.getElementById('event-json').textContent=JSON.stringify({id:e.id,type:e.type,title:e.title,illustrative:true,source_references:e.evidence.map(label=>({label,url:null})),verification:{status:'pending_review',checked_claims:[],unresolved:['Inspect the original source before acting.']},suggested_routes:e.agents},null,2);}
document.querySelectorAll('[data-event]').forEach(button=>button.addEventListener('click',()=>{selected=button.dataset.event;document.querySelectorAll('[data-event]').forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});renderEvent();}));
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{const json=button.dataset.view==='json';document.getElementById('event-summary').hidden=json;document.getElementById('event-json').hidden=!json;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));}));
renderEvent();
