"""Third accuracy pass: regressions from a real morning edition (October 6, 2026, 1.0.0rc9).

That edition joined different stories through an everyday word ('adding', 'national'), let a
single-outlet story into Top Stories while corroborated news waited, put "Uncertain trend" on every
card, called reworded stories "updated", and showed summaries that repeated themselves, stated
numbers the sources do not, or copied the page's own voice ('Every time you ask ChatGPT ...').
"""

from __future__ import annotations

import random

from agent_reach.models import CleanedTrendItem, RawTrendItem, SourceName
from agent_reach.pipeline.clusterer import LinkIndex
from agent_reach.pipeline.event_identity import IdentityGate, cohesive_groups
from tests.test_accuracy import NOW, REAL

#: (source, title, context) as they appeared in the edition
MORNING = [
    # 1-7: the watermark story, a cartoon story and an Apple lawsuit joined by 'ChatGPT/OpenAI' + 'adding'
    ("hackernews", "ChatGPT is adding real cartoonists' signatures to fake New Yorker cartoons", ""),
    ("news_rss", "OpenAI will start watermarking ChatGPT's text in the EU",
     "OpenAI will watermark ChatGPT and Codex text in the EU to comply with the AI Act."),
    ("news_rss", "OpenAI is adding invisible watermarks to ChatGPT and Codex text in the EU",
     "OpenAI is preparing to add invisible watermarks to text generated by ChatGPT and Codex in the European Union."),
    ("news_rss", "ChatGPT is not only using New Yorker cartoonists' style but also adding their signatures to the fake "
                 "cartoons it creates, which have gone viral on social media (Andrew Deck/Nieman Lab)", ""),
    ("news_rss", "Apple accuses OpenAI of improperly adding new arguments to trade secrets case",
     "A few days ago, OpenAI accused Apple of improperly adding new evidence to its trade secrets case."),
    ("news_rss", "OpenAI rolls out weak sauce watermarking for AI text", "Compliance, we've heard of it"),
    ("news_rss", "OpenAI Is Adding Text Watermarks in the EU Because Regulation Works",
     "On Monday, OpenAI announced that it would start inserting an invisible watermark."),
    # 8-10: the AI czar and a cable lobby lawsuit joined by 'Trump' + 'national'
    ("news_rss", "Trump names national intelligence chief Jay Clayton as new AI czar",
     "Director of national intelligence Jay Clayton is the new White House AI czar, President Trump said on Sunday."),
    ("google_news", "Trump names national intelligence director Jay Clayton to lead a new federal AI task force", ""),
    ("news_rss", "Cable lobby to sue Trump FCC over repeal of national TV ownership cap",
     "Cable industry to sue, says FCC can't repeal TV ownership limit set by Congress."),
    # 11-23: corroborated stories of the same edition that must stay together
    ("news_rss", "Trump says his super PAC will now pay for controversial taxpayer-funded promo ads", ""),
    ("news_rss", "After bipartisan criticism, Trump says taxpayers' dollars will no longer be used for TV ads "
                 "promoting him", ""),
    ("news_rss", "Trump says he will pay for 'Patriotic Ads' himself after facing backlash from Democrats", ""),
    ("google_news", "Trump reverses course, says he won't use taxpayer money for campaign-style ads", ""),
    ("google_news", "Spain's housing crisis bursts into the spotlight at snap election", ""),
    ("google_news", "Spain's prime minister calls snap election aiming to seize momentum over housing crisis", ""),
    ("news_rss", "What to know about Spain's housing protests sparked by an 87-year-old woman's eviction", ""),
    ("news_rss", "Separatist party projected to win Quebec election, adding new test to Canada's unity", ""),
    ("news_rss", "Canada: Quebec separatists return to power, promise new independence referendum", ""),
    ("google_news", "Parti Quebecois Returns to Power, Reviving Quebec Sovereignty Push", ""),
    ("news_rss", "U.S. B-1 bombers evacuated from UK base because of threat of Iranian drone attack", ""),
    ("news_rss", "Potential Iranian Drone Attack Led to Exit of U.S. Aircraft From British Air Base", ""),
    ("news_rss", "Trump says 'threat' led US to pull bombers from RAF Fairford", ""),
    # 24-28: from an rc10 run on the same morning: 'Trump' + 'ahead' joined a diesel order to midterm items
    ("news_rss", "Trump allows cheaper, dyed diesel on highways to blunt historic fuel-cost spike ahead of midterms", ""),
    ("google_news", "Trump Signs Order to Ease Limits on Diesel Variety to Curb Costs", ""),
    ("youtube", "Trump signs order to expand access to tax-exempt diesel", ""),
    ("news_rss", "Trump Rallies for Republicans Ahead of Midterm Elections", ""),
    ("news_rss", "Republicans fight red-state midterm chaos with hundreds of millions in late money", ""),
    # 29-30: a second rc10 run joined these to the diesel order through 'midterms'
    ("news_rss", "Jimmy Kimmel has a scathing response to Trump promising $5k if Republicans win the midterms", ""),
    ("news_rss", "Trump announces $90 payments for seniors on Medicare ahead of midterm elections for premium costs", ""),
    # 31-36: a third rc10 run merged the medicine Nobel (October 5) and the physics Nobel (October 6)
    ("news_rss", "Nobel medicine prize goes to 3 scientists for research into brain activity", ""),
    ("news_rss", "Medicine Nobel awarded for brain 'switch' that controls neurons with light", ""),
    ("news_rss", "California scientist wins a Nobel Prize, then makes school lunches for his kids", ""),
    ("news_rss", "Nobel Prize in Physics goes to Francis Halzen for discovering neutrinos, described as 'ghost-like "
                 "messages from space'", ""),
    ("news_rss", "Nobel prize in physics awarded for discovery of high-energy neutrinos", ""),
    ("news_rss", "Francis Halzen wins 2026 Nobel Prize in Physics", ""),
    # 37-38: ... and joined these through 'games' + 'consoles' (no name in common)
    ("google_news", "Modders discover way to play PS5 games on Xbox consoles", ""),
    ("google_news", "'Chipflation' is driving up the cost of video games and consoles, and prices show no signs of easing",
     ""),
    # 39-40: a pair with no name in common that is one story (rare shared words still link it)
    ("news_rss", "Scientists find new antibiotic in soil bacteria", ""),
    ("news_rss", "New antibiotic discovered in soil could fight superbugs", ""),
    # 41-44: a fourth rc10 run joined these through 'hit' + 'cuts' and 'NASA' + 'space'
    ("news_rss", "FBI's spy hunting squads hit with deep cuts even as foreign espionage threats soar", ""),
    ("news_rss", "Samsung 9100 Pro SSDs slashed up to 41% while supplies last - huge price cuts hit all capacities "
                 "from 1TB to 8TB", ""),
    ("google_news", "NASA's Prima space telescope would aim to see what James Webb can't", ""),
    ("youtube", "NASA's SpaceX Crew-12 Farewell and International Space Station Change of Command", ""),
    # 45: a sixth rc10 run joined this to 37 (PS5 games on Xbox) through 'Xbox' + 'games'
    ("news_rss", "Gears of War: E-Day studio finds a way to get more performance from Xbox Series S - one that other "
                 "Xbox games can use", ""),
    # 46-52: the user's 8:03 AM edition joined these through a newsletter digest, a two-headline title and
    # 'raised ... million'
    ("news_rss", "Trump allows cheaper, dyed diesel on highways to blunt historic fuel cost spike ahead of midterms", ""),
    ("news_rss", "First Thing: 'deranged' and 'dangerous' Trump calls for Iran to strike US cities amid historic "
                 "ratings low", ""),
    ("news_rss", "Yankees bumble through 'really rough night' in Game 2 loss to Rays", ""),
    ("news_rss", "Yankees staring at sweep after comedy of errors in ALDS Game 2 | Falcons run roughshod over Saints", ""),
    ("news_rss", "Kellen Moore: Really disappointing how Saints played on an incredible night in New Orleans", ""),
    ("news_rss", "AI agents don't always understand how companies work. This startup raised $5.2 million to solve that.",
     ""),
    ("news_rss", "Marcus Mumford & Carey Mulligan Raised $7.65 Million For Children in War Zones at Annual Wassail "
                 "Benefit Charity Show", ""),
    # 53-54: joined through 'Meta' + 'safety' in a later run
    ("news_rss", "Ofcom investigates Meta over Instagram Instants safety checks", ""),
    ("news_rss", "OpenAI, Anthropic, Meta, Google stop short of AI safety guarantee", ""),
    # 55: a trend fragment joined to the AI czar (8) through 'national'
    ("google_trends", "National Taco Day", ""),
]


def _index() -> LinkIndex:
    """The morning stories inside a run of realistic size (a word in 30 of 1,000 items is not rare)."""
    rng = random.Random(1)
    words = ["".join(rng.choice("bcdfghklmnprstvz") + rng.choice("aeiou") for _ in range(4)) for _ in range(3000)]
    padding = [("news_rss", " ".join(rng.sample(words, 6)), "") for _ in range(1000)]
    # 'games' was in 17 of the run's 1,352 titles (sports and gaming): as common here
    padding += [("news_rss", " ".join(rng.sample(words, 5)) + " games", "") for _ in range(15)]
    items = []
    for i, (source, title, ctx) in enumerate(MORNING + REAL + padding, start=1):
        raw = RawTrendItem(title=title, source=SourceName(source), timestamp=NOW)
        items.append(CleanedTrendItem(**raw.model_dump(), item_id=i, normalized_title=title, heuristic_score=0.6,
                                      context=ctx or None))
    return LinkIndex(items, items)


INDEX = _index()


def _groups(ids: list[int]) -> list[list[int]]:
    return sorted((sorted(g) for g in INDEX.components(ids, [])), key=lambda g: (-len(g), g))


def _groups_embedded(ids: list[int]) -> list[list[int]]:
    """Grouping when the embedding model agrees that the reports are close (identical vectors)."""
    gate = IdentityGate(INDEX, {i: [1.0] for i in ids})
    return sorted((sorted(g) for g in cohesive_groups(ids, gate)), key=lambda g: (-len(g), g))


# ---------------------------------------------------------------- story membership
def test_an_everyday_word_does_not_link_two_stories():
    assert _groups([1, 2, 3, 4, 5, 6, 7]) == [[2, 3, 6, 7], [1, 4], [5]]
    assert _groups([8, 9, 10]) == [[8, 9], [10]]
    groups = _groups([24, 25, 26, 27, 28, 29, 30])
    assert [24, 25, 26] in groups and not any({24, 25, 26} & set(g) and {27, 28, 29, 30} & set(g) for g in groups)
    assert _groups([41, 42]) == [[41], [42]]
    assert _groups([43, 44]) == [[43], [44]]
    assert _groups([37, 45]) == [[37], [45]]


def test_shopping_event_roundups_are_not_news():
    from agent_reach.pipeline.cleaner import PROMO_RX

    for title in ("Prime Day Apple Watch deals: Series 12 all-time low, Ultra 4 $100 off, ceramic, more",
                  "Samsung Frame TVs are hitting all-time lows on October Prime Day - save up $600",
                  "2026's Biggest Blockbuster Games Just Received Their First Major Discounts in Amazon's Prime Sale"):
        assert PROMO_RX.search(title), title
    assert not PROMO_RX.search("Amazon shares fall after Prime Day sales disappoint investors")


def test_currency_signs_keep_their_meaning_in_ascii():
    from agent_reach.pipeline.cleaner import normalize_text

    assert normalize_text("the $1.9tn (£1.4tn) company") == "the $1.9tn (GBP 1.4tn) company"


def test_different_nobel_prizes_are_different_stories():
    # rc12: 'California scientist wins a Nobel Prize, then makes school lunches' does not say which prize; it
    # shares only the name 'Nobel Prize' with the medicine reports, so it is not chained into either story.
    assert _groups([31, 32, 33, 34, 35, 36]) == [[34, 35, 36], [31, 32], [33]]


def test_titles_with_no_name_in_common_link_only_through_rare_words():
    assert _groups([37, 38]) == [[37], [38]]
    assert _groups([39, 40]) == [[39, 40]]


def test_one_shared_key_name_is_not_the_same_story():
    from agent_reach.daily.changes import compare_editions
    from agent_reach.daily.edition import same_topic
    from tests.daily_fakes import make_story

    entity = "eac557a1a7f3"  # the id of the entity set ['Donald Trump']
    blog = make_story(headline="Trump Claims He's 'Doing Great' Amid Record Low Approval Rating", entity_id=entity)
    diesel = make_story(headline="Trump Signs Order to Ease Diesel Fuel Costs", entity_id=entity)
    blog.entities = diesel.entities = ["Donald Trump"]
    assert not same_topic(blog, diesel)
    ch = compare_editions(_edition_on(5, [blog]), _edition_on(6, [diesel]))
    assert [c.headline for c in ch.new] == [diesel.headline] and ch.updated == []
    blog.entities = diesel.entities = ["Donald Trump", "Diesel"]  # a real shared entity set still matches
    assert same_topic(blog, diesel)


def test_corroborated_stories_of_the_edition_stay_together():
    # (the BBC Quebec title, 18, shares only names with the others and never linked by title alone)
    for ids in ([11, 12, 13, 14], [19, 20], [21, 22]):
        assert _groups(ids) == [ids]
    # rc12: 'What to know about Spain's housing protests ...' shares only 'housing' with the snap-election
    # reports: without an embedding nothing confirms it, with an agreeing embedding it joins
    assert _groups([15, 16, 17]) == [[15, 16], [17]]
    assert _groups_embedded([15, 16, 17]) == [[15, 16, 17]]
    # rc12, precision first: "Trump says 'threat' led US to pull bombers from RAF Fairford" shares 'bombers' +
    # 'threat' with the B-1 report but only the word 'led' with 'Potential Iranian Drone Attack Led to Exit of
    # U.S. Aircraft From British Air Base'; linked to one of two members, it is not chained in by title alone
    # (in a real run its page text and the embedding can still support it)
    assert _groups([21, 22, 23]) == [[21, 22], [23]]


# ---------------------------------------------------------------- Top Stories and sections
#: (headline, category, relevance, evidence level) in the pipeline's rank order, as in the edition
RANKED = [
    ("US Bombers Removed from UK Base Due to Iranian Threat", "News", 9, "strong"),
    ("Teen Loses Hand in France School Protests", "News", 8, "strong"),
    ("Russian Lab Worker Dies of Pneumonic Plague", "News", 8, "strong"),
    ("OpenAI to Watermark ChatGPT Text in EU", "Tech", 8, "strong"),
    ("South Korea's President Says AI May Have Been Used in Bank Hacks", "News", 8, "moderate"),
    ("Trump Names National Intelligence Chief as New AI Czar", "Tech", 8, "strong"),
    ("Trump Suggests Letting Iran 'Take Out' Los Angeles or San Diego", "News", 8, "moderate"),
    ("Pentagon Stops Using Anthropic AI Tools", "Tech", 8, "limited"),
    ("Scientists Win Nobel Prize for Optogenetics", "Science & AI", 8, "strong"),
    ("LIV Golf Secures Potential $300m Investment", "Sports", 7, "moderate"),
    ("Tigray Rebel Groups 'Forcibly Recruiting Boys as Young as 15' as Fighting Spreads", "News", 7, "limited"),
    ("Trump Reverses Course on Campaign Ads", "News", 7, "strong"),
    ("Spain's Housing Crisis Bursts into the Spotlight", "News", 7, "strong"),
    ("Parti Quebecois Returns to Power in Quebec Election", "News", 7, "strong"),
]


def _ranked_stories():
    from datetime import datetime, timezone

    from agent_reach.daily.strength import EvidenceStrength
    from tests.daily_fakes import make_story

    now = datetime.now(timezone.utc)
    stories = []
    for i, (headline, category, relevance, level) in enumerate(RANKED, start=1):
        s = make_story(i, headline=headline, category=category, now=now, relevance=relevance)
        s.evidence_strength = EvidenceStrength(level=level, points=1 if level == "limited" else 5)
        stories.append(s)
    return stories, now


def test_corroborated_news_beyond_the_category_cap_comes_before_a_single_outlet_story():
    from agent_reach.daily.edition import select_stories
    from agent_reach.daily.prefs import DailyPrefs

    stories, now = _ranked_stories()
    sel = select_stories(stories, DailyPrefs(max_stories=10, max_per_category=4), now=now)
    top = [s.headline for s in sel.top]
    assert len(top) == 10
    assert "Pentagon Stops Using Anthropic AI Tools" not in top
    assert "Trump Reverses Course on Campaign Ads" in top
    assert sel.filled_from_held_back == 1


def test_a_single_outlet_story_rated_9_waits_for_corroborated_news():
    from datetime import datetime, timezone

    from agent_reach.daily.edition import select_stories
    from agent_reach.daily.prefs import DailyPrefs
    from agent_reach.daily.strength import EvidenceStrength
    from tests.daily_fakes import make_story

    # a second rc10 run (pipeline order and relevance as stored): 'Christa Pike' (1 report, rated 9) took
    # a place while the plague story (5 reports) waited; rc9's rules give exactly that run's Top Stories
    rows = [("Method for Controlling Brain Cells with Light Wins Nobel", "Science & AI", 9, "strong"),
            ("Christa Pike's Failed Execution Sparks Outrage", "News", 9, "limited"),
            ("Yemen Government Forces Advance on Bab el-Mandeb", "News", 9, "strong"),
            ("Trump Signs Order to Ease Limits on Diesel Variety to Curb Costs", "News", 8, "strong"),
            ("US Bombers Removed from RAF Fairford Due to Threat", "News", 8, "strong"),
            ("Spain's Housing Crisis Bursts into Spotlight", "News", 8, "strong"),
            ("Caleb Flynn Sentenced to Life in Prison", "News", 8, "moderate"),
            ("Oracle Health Data Breach Affects 20 Million", "Tech", 8, "limited"),
            ("Meta and Microsoft Cut Back from Claude", "Science & AI", 8, "limited"),
            ("Phoebe Bridgers, Massive Attack, Caroline Polachek to Headline Primavera 2027", "Entertainment", 8,
             "limited"),
            ("Russia Reports a Worker at a Siberian Plague Institute Got Pneumonia from an Unknown Cause and Died",
             "News", 7, "strong"),
            ("France Braces for Day of School Blockades and Street Protests", "News", 7, "strong"),
            ("Kenya Confirms First Ebola Case", "News", 7, "strong"),
            ("ChatGPT Creates Fake New Yorker Cartoons with Real Signatures", "Tech", 7, "moderate"),
            ("OpenAI to Watermark ChatGPT Text in EU", "Science & AI", 7, "moderate"),
            ("AI Billionaire Sam Altman Says World Should Accept 'Bad Things' for AI Benefits", "Internet Culture", 7,
             "moderate")]
    now = datetime.now(timezone.utc)
    stories = []
    for i, (headline, category, relevance, level) in enumerate(rows, start=1):
        s = make_story(i, headline=headline, category=category, now=now, relevance=relevance)
        s.evidence_strength = EvidenceStrength(level=level, points=1 if level == "limited" else 5)
        stories.append(s)
    top = [s.headline for s in select_stories(stories, DailyPrefs(max_stories=10, max_per_category=4), now=now).top]
    assert "Christa Pike's Failed Execution Sparks Outrage" not in top
    assert any(h.startswith("Russia Reports a Worker") for h in top)


def test_sections_list_corroborated_stories_before_single_outlet_ones():
    from agent_reach.daily.edition import select_stories
    from agent_reach.daily.prefs import DailyPrefs

    stories, now = _ranked_stories()
    sel = select_stories(stories, DailyPrefs(max_stories=10, max_per_category=4), now=now)
    news = [s.headline for s in sel.stories if s.category.value == "News"]
    assert news[-1].startswith("Tigray Rebel Groups")
    assert news.index("Trump Reverses Course on Campaign Ads") < news.index(news[-1])
    tech = [s.headline for s in sel.stories if s.category.value == "Tech"]
    assert tech[-1] == "Pentagon Stops Using Anthropic AI Tools"


# ---------------------------------------------------------------- trend labels and notes
def test_uncertain_momentum_is_said_once_not_on_every_card():
    from agent_reach.daily.edition import Selection, edition_notes
    from agent_reach.daily.prefs import DailyPrefs
    from tests.daily_fakes import make_story

    old_card = make_story(labels=["Uncertain trend", "Hot"])  # as stored by rc9
    assert old_card.labels == ["Hot"]
    stories, _ = _ranked_stories()
    for s in stories:
        s.momentum, s.velocity_basis = "UNCERTAIN", "coverage_uncertain"
    notes = edition_notes(Selection(stories=stories), DailyPrefs())
    assert sum("No Hot or Rising labels today" in n for n in notes) == 1
    stories[0].momentum, stories[0].velocity_basis = "RISING", "historical"
    assert not any("No Hot or Rising labels today" in n for n in edition_notes(Selection(stories=stories), DailyPrefs()))


def test_notes_agree_in_number():
    from agent_reach.daily.edition import Selection, edition_notes
    from agent_reach.daily.prefs import DailyPrefs
    from tests.daily_fakes import make_story

    one = edition_notes(Selection(stories=[make_story()], dropped_unsupported=1, secondary=1), DailyPrefs())
    assert "1 ranked group was omitted because it had no citable factual sentence." in one
    assert ("1 opinion column or video clip is listed after the news in its section and kept out of Top Stories."
            in one)
    two = edition_notes(Selection(stories=[make_story()], dropped_unsupported=2, secondary=2), DailyPrefs())
    assert "2 ranked groups were omitted because they had no citable factual sentence." in two
    assert any("listed after the news in their sections" in n for n in two)


# ---------------------------------------------------------------- what changed
def _edition_on(day: int, stories):
    from datetime import datetime, timezone

    from tests.daily_fakes import make_edition

    return make_edition(stories, started=datetime(2026, 10, day, 9, 0, tzinfo=timezone.utc), run_id=f"run-{day}")


def _with_report(story, publisher: str, title: str):
    from agent_reach.daily.edition import EvidenceLink

    host = publisher.lower().replace(" ", "") + ".test"
    story.evidence.append(EvidenceLink(item_id=2, source="news_rss", source_name="News feeds", title=title,
                                       url=f"https://{host}/{len(story.evidence)}", publisher=publisher))
    return story


def test_rewording_the_same_reports_is_not_an_update():
    from agent_reach.daily.changes import compare_editions
    from tests.daily_fakes import make_story

    url = "https://bbc.test/data-centres-scotland"
    before = make_story(headline="Data Centres Spark Concern in Scotland", url=url,
                        sentences=["At least 23 huge data centres are planned in Scotland."])
    after = make_story(headline="Why Are Data Centres Such a Big Deal in Scotland?", url=url,
                       sentences=["Campaigners are concerned about at least 23 data centres planned in Scotland."],
                       why="Residents near the planned sites face higher water use.")
    ch = compare_editions(_edition_on(5, [before]), _edition_on(6, [after]))
    assert ch.updated == [] and ch.unchanged == 1


def test_new_reporting_or_a_headline_from_new_reports_is_an_update():
    from agent_reach.daily.changes import compare_editions, headline_has_news
    from tests.daily_fakes import make_story

    url = "https://bbc.test/bombers"
    before = make_story(headline="US Bombers Removed from UK Base Due to Iranian Threat", url=url)
    after = _with_report(make_story(headline="US Bombers Removed from UK Base Due to Iranian Threat", url=url),
                         "New York Times", "Potential Iranian Drone Attack Led to Exit of U.S. Aircraft From British Air Base")
    ch = compare_editions(_edition_on(5, [before]), _edition_on(6, [after]))
    assert [c.detail for c in ch.updated] == ["new reporting from The New York Times"]

    old = make_story(headline="Trump Approval Ratings Plummet to New Low", url="https://guardian.test/polls")
    new = _with_report(make_story(headline="Trump Claims He's 'Doing Great' Amid Record Low Approval Rating",
                                  url="https://guardian.test/polls"),
                       "Wire One", "Trump claims he's 'doing great' as his approval rating sinks to record low")
    assert headline_has_news(new, old)
    reworded = make_story(headline="Trump Approval Hits Record Low in New Polls", url="https://guardian.test/polls")
    assert not headline_has_news(reworded, old)

    # a second rc10 run: the new headline is a title the previous edition already cited
    nobel_url = "https://ap.test/nobel"
    nobel = _with_report(make_story(headline="Scientists Win Nobel Prize for Optogenetics", url=nobel_url),
                         "Science - News", "Method for controlling brain cells with light wins Nobel")
    retitled = _with_report(_with_report(make_story(headline="Method for Controlling Brain Cells with Light Wins Nobel",
                                                    url=nobel_url),
                                         "Science - News", "Method for controlling brain cells with light wins Nobel"),
                            "Phys.org", "California scientist wins a Nobel Prize, then makes school lunches for his kids")
    retitled.evidence[1].url = nobel.evidence[1].url
    assert not headline_has_news(retitled, nobel)
    ch = compare_editions(_edition_on(5, [nobel]), _edition_on(6, [retitled]))
    assert [c.detail for c in ch.updated] == ["new reporting from Phys.org"]


def test_a_story_carried_over_from_yesterday_is_not_fading():
    from agent_reach.daily.changes import compare_editions
    from tests.daily_fakes import make_story

    url = "https://cnbc.test/plague"
    yesterday = make_story(headline="Russian Lab Worker Dies of Pneumonic Plague", url=url, items=14)
    today = make_story(headline="Russian Lab Worker Dies of Pneumonic Plague", url=url, items=9)
    assert compare_editions(_edition_on(5, [yesterday]), _edition_on(6, [today])).signals_down == []
    # within one day (a second revision) the same drop is still reported
    assert len(compare_editions(_edition_on(6, [yesterday]), _edition_on(6, [today])).signals_down) == 1


# ---------------------------------------------------------------- categories
def test_a_carried_over_story_keeps_its_section_unless_new_reporting_arrives():
    from agent_reach.daily.changes import keep_previous_categories
    from tests.daily_fakes import make_story

    tool_url, beam_url = "https://arstechnica.test/apple-intelligence-tool", "https://reflection.test/beam"
    previous = _edition_on(5, [
        make_story(headline="Tool Removes Apple's AI Bloatware and Frees up Storage on macOS", category="Tech",
                   url=tool_url),
        make_story(headline="Beam: Reflection's 501B Open-Weight Model", category="Science & AI", url=beam_url)])
    tool = make_story(headline="Command-line Tool Quickly Removes Apple Intelligence from macOS 27",
                      category="Science & AI", url=tool_url)
    beam = make_story(headline="Beam: Reflection's 501B Open-Weight Model", category="Tech", url=beam_url)
    assert keep_previous_categories([tool, beam], previous) == 2
    assert (tool.category.value, beam.category.value) == ("Tech", "Science & AI")

    grown = _with_report(make_story(headline="Beam: Reflection's 501B Open-Weight Model", category="Tech",
                                    url=beam_url), "The Verge", "Reflection releases Beam, a 501B open model")
    assert keep_previous_categories([grown], previous) == 0 and grown.category.value == "Tech"


def test_report_words_settle_tech_versus_science():
    from datetime import datetime, timezone

    from agent_reach.config import Settings
    from agent_reach.models import CategoryEnum
    from agent_reach.pipeline.clusterer import SemanticClusterer

    title = "Command-line tool quickly removes Apple Intelligence from macOS 27"
    raw = RawTrendItem(title=title, source=SourceName.NEWS_RSS, timestamp=datetime.now(timezone.utc),
                       description="The tool can free up over 12GB of storage.")
    item = CleanedTrendItem(**raw.model_dump(), item_id=1, normalized_title=title, heuristic_score=0.6)
    clusterer = SemanticClusterer(Settings())
    assert clusterer._guard_category(CategoryEnum.SCIENCE_AI, [item]) is CategoryEnum.TECH
    assert clusterer._guard_category(CategoryEnum.TECH, [item]) is CategoryEnum.TECH


# ---------------------------------------------------------------- headlines
def test_a_title_a_few_words_over_the_limit_is_kept_whole():
    from agent_reach.pipeline.cleaner import sanitize_headline
    from agent_reach.pipeline.clusterer import HEADLINE_MAX_WORDS, HEADLINE_STRETCH_WORDS

    def headline(title: str) -> str:
        return sanitize_headline(title, HEADLINE_MAX_WORDS, HEADLINE_STRETCH_WORDS)

    assert headline("‘Ba’s Book’: How Making the Heartfelt Hybrid Film Exploring Trauma Brought a Family "
                    "Closer Together") == ("'Ba's Book': How Making the Heartfelt Hybrid Film Exploring Trauma "
                                           "Brought a Family Closer Together")
    assert headline("Cohere pitches North 2 as the enterprise AI control room that works with any model") == \
        "Cohere Pitches North 2 as the Enterprise AI Control Room That Works with Any Model"
    long_title = " ".join(["word"] * 12 + ["and", "then", "more", "words", "keep", "coming", "here", "now", "too"])
    assert len(headline(long_title).split()) <= HEADLINE_MAX_WORDS  # beyond the stretch: still cut


def test_a_title_that_opens_with_a_quotation_keeps_both_quotes():
    from agent_reach.pipeline.cleaner import sanitize_headline

    assert sanitize_headline("“Your Pay Is Not My Concern”: Millionaire TikToker Refuses To Tip, Sparks a "
                             "Debate") == '"Your Pay Is Not My Concern": Millionaire TikToker Refuses to Tip, Sparks a Debate'


def test_a_domain_that_is_the_subject_is_kept():
    from agent_reach.pipeline.cleaner import sanitize_headline, sanitize_summary

    assert sanitize_headline("Example.com just launched the biggest redesign in decades") == \
        "Example.com Just Launched the Biggest Redesign in Decades"
    assert "techcrunch" not in sanitize_headline("Startup raises $40M for chips via techcrunch.com").lower()
    assert sanitize_summary("Example.com's redesign is its biggest in decades.").startswith("Example.com's redesign")


def test_live_blogs_are_not_titles_summaries_or_stories():
    from datetime import datetime, timezone

    from agent_reach.daily.edition import lead_sentence, select_stories
    from agent_reach.daily.prefs import DailyPrefs
    from agent_reach.models import MacroCluster
    from agent_reach.pipeline.cleaner import sanitize_headline
    from agent_reach.pipeline.clusterer import SemanticClusterer
    from tests.daily_fakes import make_story

    live = "Trump claims he’s ‘doing great’ as his approval rating sinks to record low – as it happened"
    assert sanitize_headline(live) == "Trump Claims He's 'Doing Great' as His Approval Rating Sinks to Record Low"

    def item(i: int, title: str, context: str, score: float) -> CleanedTrendItem:
        raw = RawTrendItem(title=title, source=SourceName.NEWS_RSS, timestamp=NOW)
        return CleanedTrendItem(**raw.model_dump(), item_id=i, normalized_title=title, heuristic_score=score,
                                context=context)

    blog = item(1, live, "This live blog is now closed. | Before boarding a flight to Nebraska, Donald Trump answered "
                         "more questions from reporters about his polling numbers.", 0.9)
    poll = item(2, "Trump's approval hits new low among Hispanic voters ahead of midterms",
                "A new poll shows the president's approval among Hispanic voters fell to a record low this month.", 0.5)
    assert SemanticClusterer._best_member_title([blog, poll]) == poll.normalized_title
    cluster = MacroCluster(cluster_id="c", headline="Trump Approval Hits Record Low", category="News",
                           relevance_score=6, summary="S.", velocity_score=50.0, raw_item_count=2,
                           member_item_ids=[1, 2])
    assert lead_sentence(cluster, {1: blog, 2: poll}).startswith("A new poll shows")

    now = datetime.now(timezone.utc)
    blog_story = make_story(1, headline="Trump Claims He's 'Doing Great' Amid Record Low Approval Rating", now=now)
    blog_story.evidence[0].title, blog_story.evidence[0].excerpt = live, "This live blog is now closed."
    sel = select_stories([blog_story, make_story(2, now=now)], DailyPrefs(), now=now)
    assert sel.dropped_live_blog == 1 and [s.rank for s in sel.stories] == [2]


# ---------------------------------------------------------------- summary text
def test_summary_numbers_must_come_from_the_sources():
    from agent_reach.daily.edition import body_sentences

    source = ("Beam: Reflection's 501B open-weight model. We are introducing Beam, Reflection's first open-weight model. "
              "Beam is a sparse Mixture-of-Experts model with 501 billion total parameters, 23 billion active, built "
              "for coding, reasoning, and agentic tasks.")
    assert body_sentences("Reflection introduced Beam, a sparse Mixture-of-Experts model with 501 billion total "
                          "parameters, 23 billion weights, and 1.4 billion neurons.", source) == []
    assert body_sentences("Reflection introduced Beam, a sparse Mixture-of-Experts model with 501 billion total "
                          "parameters and 23 billion active.", source) != []


def test_a_sentence_that_repeats_itself_loses_the_repeat():
    from agent_reach.daily.edition import body_sentences

    source = ("Opus 5.5 agents discover two room-temperature magnetic semiconductor candidates. We are sharing two "
              "candidate magnets for next-generation computer memory, found by a team of Claude Opus 5.5 agents.")
    assert body_sentences("A team of Claude Opus 5.5 agents discovered two candidate magnets for next-generation "
                          "computer memory, found by a team of Claude Opus 5.5 agents.", source) == [
        "A team of Claude Opus 5.5 agents discovered two candidate magnets for next-generation computer memory."]


def test_copied_page_voice_fragments_and_empty_restatements_are_dropped():
    from agent_reach.daily.edition import body_sentences, lead_sentence
    from agent_reach.models import MacroCluster

    scotland = ("Why are data centres such a big deal in Scotland? At least 23 huge data centres are planned in Scotland, "
                "causing significant concern for campaigners. | Every time you ask ChatGPT a question, read a Google "
                "summary or make an online bank payment, a data centre is working behind the scenes.")
    summary = ("At least 23 huge Data Centres are planned in Scotland, causing significant concern for campaigners. "
               "Every time you ask ChatGPT a question, read a Google summary or make an online bank payment, a data "
               "centre is working behind the scenes.")
    assert body_sentences(summary, scotland) == [summary.split(" Every time")[0]]

    tubefilter = ("There's now a monthly virtual support group for creators struggling with their mental health. Over the "
                  "past five years, as our industry stepped into this new era of short-form mega consumption, AI-pushing "
                  "productivity platforms, and Hollywood nods | \"Content creator\" became a widely recognized career, "
                  "and the unique stressors that come along with it received more serious acknowledgment.")
    summary = ("A monthly virtual support group has been established for Creators struggling with their mental health. "
               "Over the past five years, as our industry stepped into this new era of short-form mega consumption, "
               "AI-pushing productivity platforms, and Hollywood nods.")
    assert body_sentences(summary, tubefilter) == [summary.split(" Over the")[0]]
    assert body_sentences("Over the past five years, as the industry stepped into a new era of short-form video, "
                          "AI tools, and Hollywood nods.", tubefilter) == []  # no main clause

    debugbear = ("Example.com just launched the biggest redesign in decades. A look at the history of visual changes to "
                 "example.com. | example.com is a reserved domain name set aside by the Internet Assigned Numbers "
                 "Authority (IANA) for documentation purposes.")
    assert body_sentences("The redesign is the biggest in decades.", debugbear,
                          "Example.com Just Launched the Biggest Redesign in Decades") == []
    raw = RawTrendItem(title="Example.com just launched the biggest redesign in decades", source=SourceName.HACKERNEWS,
                       timestamp=NOW)
    item = CleanedTrendItem(**raw.model_dump(), item_id=1, normalized_title=raw.title, heuristic_score=0.6,
                            context=debugbear.split(". ", 1)[1])
    cluster = MacroCluster(cluster_id="c", headline="Example.com Just Launched the Biggest Redesign in Decades",
                           category="Tech", relevance_score=6, summary="The redesign is the biggest in decades.",
                           velocity_score=50.0, raw_item_count=1, member_item_ids=[1])
    assert lead_sentence(cluster, {1: item}, cluster.headline).startswith("example.com is a reserved domain name")


def test_abbreviations_do_not_end_a_sentence():
    from agent_reach.daily.edition import SENTENCE_SPLIT_RX
    from agent_reach.pipeline.cleaner import sanitize_summary

    text = ("TikTok outlined its preparation measures for the upcoming U.S. midterm elections. The app stressed its "
            "security and reliability.")
    assert sanitize_summary(text) == text  # was 'the upcoming U.S.' + 'Midterm elections.' (fifth rc10 run)
    assert len(SENTENCE_SPLIT_RX.split("He could lose his No. 1 ranking. He will return in 2027.")) == 2


# ---------------------------------------------------------------- the user's first rc10 edition (6:49 AM)
def test_a_title_like_gov_never_becomes_a_sentence():
    from agent_reach.daily.edition import body_sentences
    from agent_reach.pipeline.cleaner import sanitize_summary

    text = ("President Trump suggested during a campaign rally that Iran could 'take out' Los Angeles and San Diego. "
            "Gov. Gavin Newsom called the remarks deranged and dangerous.")
    assert sanitize_summary(text) == text  # was '... San Diego.' + 'Gov.' + 'Gavin Newsom ...'
    source = ("Trump suggests Iran could 'take out' Los Angeles and San Diego during a campaign rally. Gov.")
    assert body_sentences("President Trump suggested during a campaign rally that Iran could 'take out' Los Angeles "
                          "and San Diego. Gov.", source) == [
        "President Trump suggested during a campaign rally that Iran could 'take out' Los Angeles and San Diego."]


def test_live_blogs_named_after_their_section_are_live_blogs():
    from agent_reach.pipeline.cleaner import is_live_blog, sanitize_headline

    guardian = "Trump says he will stop using taxpayer funds for self-promoting ads after backlash – US politics live"
    assert is_live_blog(guardian) and is_live_blog("Ukraine war live: Kyiv hit by drones overnight")
    assert sanitize_headline(guardian) == "Trump Says He Will Stop Using Taxpayer Funds for Self-promoting Ads After Backlash"
    assert not is_live_blog("Where to watch Arsenal against Chelsea live")


def test_why_it_matters_is_not_a_cause_a_detail_or_a_repeat():
    from agent_reach.daily.brief import apply_brief, concrete_effect
    from tests.daily_fakes import make_story

    assert not concrete_effect("The decision to stop using taxpayer funds for the ads is a response to intense criticism.")
    assert not concrete_effect("The investigation is examining whether Meta carried out adequate risk assessment as "
                               "required by the Online Safety Act.")
    wiki = make_story(headline="OpenAI 'Rogue' Agents Found on Wikimedia Projects",
                      sentences=["Rogue OpenAI agents made unauthorized Wikipedia edits.",
                                 "These types of successful intrusions can expose sensitive data and compromise online "
                                 "services."])
    wiki.evidence[0].excerpt = ("These types of successful intrusions can expose sensitive data or disrupt website "
                                "services that users rely on. Wikipedia gets up to 15 million visitors per day.")
    assert apply_brief(wiki, "", "These types of successful intrusions can expose sensitive data or disrupt website "
                                 "services that users rely on.") == (0, 0)


def test_titles_keep_decades_and_ellipses_readable():
    from agent_reach.pipeline.cleaner import sanitize_headline

    assert sanitize_headline("The 10 Greatest Stephen King Books of the '80s, Ranked") == \
        "The 10 Greatest Stephen King Books of the '80s, Ranked"
    assert sanitize_headline("PewDiePie is setting AI free... and OpenAI is furious") == \
        "PewDiePie Is Setting AI Free, and OpenAI Is Furious"


def test_ordinary_nouns_are_not_capitalised_as_names():
    from agent_reach.config import Settings
    from agent_reach.pipeline.clusterer import SemanticClusterer

    raw = RawTrendItem(title="Scientists Find a Hidden Network of Tiny Channels The Brain May Use to Flush Out Toxic "
                             "Alzheimer's Proteins", source=SourceName.NEWS_RSS, timestamp=NOW)
    item = CleanedTrendItem(**raw.model_dump(), item_id=1, normalized_title=raw.title, heuristic_score=0.6,
                            context="Tiny channels in the brain may help clear toxic Alzheimer's proteins, a study in "
                                    "mice suggests.")
    out = SemanticClusterer(Settings())._fix_summary(
        "Researchers have discovered a network of channels in the brain that may help remove toxic Alzheimer's "
        "proteins. The channels were seen in mice.", [item], "Hidden Brain Channels", ["Brain", "Alzheimer's Proteins"])
    assert "in the brain" in out and "Alzheimer's proteins" in out


# ---------------------------------------------------------------- the user's 8:03 AM edition (revision 4)
def test_roundups_link_no_reports():
    from agent_reach.pipeline.cleaner import is_roundup

    assert is_roundup(MORNING[46][1]) and is_roundup(MORNING[48][1])
    assert not is_roundup("Command-line tool quickly removes Apple Intelligence | Ars Technica")
    assert not is_roundup("Trump Signs Executive Order to Lower Diesel Prices. What You Need To Know - October 6")
    assert _groups([46, 47]) == [[46], [47]]
    assert not any({48, 50} <= set(g) for g in _groups([48, 49, 50]))
    assert _groups([51, 52]) == [[51], [52]]


def test_a_trend_fragment_does_not_link_through_an_everyday_word():
    taco = next(i for i, it in INDEX.items.items() if it.normalized_title == "National Taco Day")
    czar = 8  # 'Trump names national intelligence chief Jay Clayton as new AI czar'
    assert not INDEX.linked(taco, czar)


def test_this_and_a_noun_does_not_open_a_summary():
    from agent_reach.daily.edition import body_sentences

    source = ("New open-weight AI models mount a comeback against China. This model is part of a new crop of powerful, "
              "Western open-weight AI systems. This year's releases narrow China's lead.")
    assert body_sentences("This model is part of a new crop of powerful, Western open-weight AI systems.", source) == []
    assert body_sentences("This year's releases narrow China's lead.", source) == ["This year's releases narrow China's lead."]


def test_casing_follows_a_sentence_case_title_when_the_page_is_silent():
    from agent_reach.config import Settings
    from agent_reach.pipeline.clusterer import SemanticClusterer

    raw = RawTrendItem(title="There's now a monthly virtual support group for creators struggling with their mental "
                             "health", source=SourceName.NEWS_RSS, timestamp=NOW)
    item = CleanedTrendItem(**raw.model_dump(), item_id=1, normalized_title=raw.title, heuristic_score=0.6,
                            context="\"Content creator\" became a widely recognized career.")
    out = SemanticClusterer(Settings())._fix_summary(
        "A monthly virtual support group is being launched for creators struggling with their mental health. It meets "
        "online.", [item], "Support Group for Creators", ["Creators", "Mental Health"])
    assert "for creators struggling with their mental health" in out


def test_a_headline_never_loses_its_main_verb_to_a_clause_cut():
    from agent_reach.pipeline.cleaner import sanitize_headline
    from agent_reach.pipeline.clusterer import HEADLINE_MAX_WORDS, HEADLINE_STRETCH_WORDS

    title = "Jim Bakker, who lost his 'PTL Club' televangelism empire in sex and money scandals, dies at 86"
    assert sanitize_headline(title, HEADLINE_MAX_WORDS, HEADLINE_STRETCH_WORDS).endswith("Dies at 86")


def test_company_abbreviations_do_not_end_a_sentence():
    from agent_reach.pipeline.cleaner import sanitize_summary

    text = ("Paramount and Warner Bros. have merged to form a new media conglomerate, Skydance. David Ellison called "
            "it a historic day.")
    assert sanitize_summary(text) == text  # was 'Paramount and Warner Bros.' + 'Have merged to form ...'


def test_a_shared_safety_is_not_the_same_story():
    raw = [("news_rss", "Ofcom investigates Meta over Instagram Instants safety checks"),
           ("news_rss", "OpenAI, Anthropic, Meta, Google stop short of AI safety guarantee")]
    ids = []
    for title in (t for _, t in raw):
        ids.append(next(i for i, it in INDEX.items.items() if it.normalized_title == title))
    assert len(INDEX.components(ids, [])) == 2


def test_version_7_settings_replace_the_independent():
    from agent_reach.daily.feeds import default_feeds
    from agent_reach.daily.prefs import DailyPrefs

    indy = "https://www.independent.co.uk/news/world/rss"  # HTTP 429 for every automated reader, 5 runs in a row
    prefs = DailyPrefs.model_validate({"prefs_version": 7, "feeds": [
        {"name": "The Independent - World", "url": indy, "category": "News"}]})
    assert [f.name for f in prefs.feeds] == ["CBS News - World"]
    assert indy not in {f.url for f in default_feeds()}


def test_price_drops_for_a_shopping_event_are_promotional():
    from agent_reach.pipeline.cleaner import PROMO_RX

    assert PROMO_RX.search("The MacBook Air Drops to Its Lowest Price Since June for Prime Day")
    assert PROMO_RX.search("Our Go-To Over-Ear Headphones Are at Their Lowest Price for Prime Day")


def test_a_summary_does_not_open_mid_thought_or_end_clipped():
    from agent_reach.daily.edition import body_sentences

    beam = "Beam: Reflection's 501B open-weight model. It is an open-weight model available through Reflection."
    assert body_sentences("It is an open-weight model available through Reflection.", beam) == []
    brain = ("Scientists find a hidden network of tiny channels the brain may use to flush out toxic Alzheimer's "
             "proteins. But tracing their journey out of the brain has proved surprisingly difficult.")
    assert body_sentences("But tracing their journey out of the brain has proved surprisingly difficult.", brain) == []
    ev = ("EV charging company plans to deploy 100,000 Nvidia GPUs in pods at its roadside sites. The move aims to offer "
          "edge inference compute using idle EV charging capacity.")
    assert body_sentences("The move aims to offer edge inference compute using idle EV charging capacity.", ev) == []
    comic = ("Tiffany Sloan is the name given to an AI-generated character that appears in numerous AI-slop Instagram "
             "Reels, often featuring her telling a joke in front of a fake...")
    assert body_sentences(comic, comic) == []
    # a pronoun after the sentence it refers to is fine
    assert len(body_sentences("Reflection released Beam, an open-weight model. It is available through Reflection.",
                              beam + " Reflection released Beam.")) == 2


# ---------------------------------------------------------------- the user's 7:24 AM edition (revision 3)
def test_a_number_must_stand_next_to_the_same_words_as_in_the_sources():
    from agent_reach.daily.edition import body_sentences, numbers_anchored

    wiki = ("OpenAI rogue agent activities found on Wikimedia projects. Wikipedia hosts over 67 million articles in "
            "more than 300 languages and gets up to 15 million visitors per day.")
    assert not numbers_anchored("Over 67 million Wikipedia hosts expose sensitive data.", wiki)
    assert body_sentences("Rogue OpenAI agents made unauthorized Wikipedia edits. Over 67 million Wikipedia hosts "
                          "expose sensitive data.", wiki + " Rogue OpenAI agents made unauthorized Wikipedia edits.") \
        == ["Rogue OpenAI agents made unauthorized Wikipedia edits."]
    beam = ("Beam is a sparse Mixture-of-Experts model with 501 billion total parameters, 23 billion active, built for "
            "coding.")
    assert not numbers_anchored("Beam's 23 billion weights make it fast.", beam)
    # the same number in other words is fine: real sentences from the October 6 editions
    for sentence, source in (
            ("Robert Kelker-Kelly, soap drama star, dies at 62.", "Days of Our Lives' Bo Brady, Dead at 62"),
            ("The lab worker, Darya Shipilova, was 28 years old.", "The death of a 28-year-old lab tech halfway"),
            ("A Nigerian military plane crash has killed all 25 people on board.",
             "Nigerian military plane crash kills all 25 on board"),
            ("Anthropic CEO Dario Amodei earned $18M last year.", "Anthropic IPO filing shows CEO Dario Amodei earned "
                                                                  "$18M in 2025"),
            ("The Falcons defeated the Saints 45-24 in a game on October 5, 2026.", "Falcons 45-24 Saints (Oct 5, 2026)"),
            ("A person is making NFL picks and score predictions for Week 5.", "Welcome to Week 5 of the NFL season")):
        assert numbers_anchored(sentence, source), sentence


def test_a_sentence_about_the_article_is_not_news():
    from agent_reach.daily.edition import body_sentences

    source = ("NFL Week 5 picks and score predictions: Ravens and Bills both lose, 49ers win thriller over Seahawks. "
              "Welcome to Week 5 of the NFL season, the author provides picks and score predictions.")
    assert body_sentences("The author provides their NFL Week 5 picks and score predictions. The Ravens and Bills are "
                          "expected to lose.", source) == ["The Ravens and Bills are expected to lose."]


def test_a_pronoun_keeps_the_sentence_it_refers_to():
    from agent_reach.daily.edition import body_sentences

    source = ("Robert Kelker-Kelly, soap drama star known for 'Days of Our Lives' turn as Bo, dies. Robert "
              "Kelker-Kelly, Days of Our Lives' Bo Brady, Dead at 62. He was best known for playing Bo Brady on "
              "'Days of Our Lives.'")
    summary = ("Robert Kelker-Kelly, soap drama star, dies at 62. He was best known for playing Bo Brady on 'Days of "
               "Our Lives'.")
    assert body_sentences(summary, source, "Robert Kelker-Kelly, Soap Drama Star, Dies at 62") == [
        "Robert Kelker-Kelly, soap drama star, dies at 62.", "He was best known for playing Bo Brady on 'Days of Our Lives'."]


def test_a_model_headline_must_use_the_reports_words():
    from agent_reach.pipeline.clusterer import headline_supported

    def item(i: int, title: str) -> CleanedTrendItem:
        raw = RawTrendItem(title=title, source=SourceName.NEWS_RSS, timestamp=NOW)
        return CleanedTrendItem(**raw.model_dump(), item_id=i, normalized_title=title, heuristic_score=0.6)

    recap = [item(1, "Falcons 45-24 Saints (Oct 5, 2026) Game Recap"), item(2, "Falcons")]
    assert not headline_supported("Falcons Edge Saints in Thursday Night Football", recap)  # a Monday game
    rout = [item(3, "Bijan Robinson, Falcons make NFC South statement in rout of Saints")]
    assert headline_supported("Bijan Robinson Leads Falcons to Rout of Saints", rout)


def test_a_sentence_cut_short_is_dropped():
    from agent_reach.daily.edition import body_sentences

    source = ("Trump names national intelligence chief Jay Clayton as new AI czar. Trump said Clayton will lead the "
              "White House's new \"Super Intelligence Force,\" which will coordinate government engagement with "
              "artificial intelligence. Director of national intelligence Jay Clayton is the new White House AI czar.")
    summary = ("US President Donald Trump has named Jay Clayton as the new White House AI Czar. Clayton will lead "
               "the government's new.")
    assert body_sentences(summary, source) == [summary.split(" Clayton will")[0]]


def test_a_detail_that_repeats_a_sentence_replaces_it_or_is_left_out():
    from agent_reach.daily.brief import apply_brief
    from tests.daily_fakes import make_story

    yemen = make_story(headline="Yemen Government Forces Advance on Bab el-Mandeb in Offensive Against Houthis",
                       sentences=["Yemen government forces, backed by 100 Saudi coalition aircraft, have advanced on "
                                  "Bab el-Mandeb in an offensive against the Houthis.",
                                  "The Houthis claimed they struck Riyadh's international airport."])
    yemen.evidence[0].excerpt = ("Operation Yemen Dawn, backed by 100 Saudi coalition aircraft, retook the town of Dhubab "
                                 "just north of the strait, as the Houthis claimed they struck Riyadh's international "
                                 "airport, an oil refinery and military bases across Saudi Arabia, and Pakistan.")
    longer = ("The Houthis claimed they struck Riyadh's international airport, an oil refinery, and military bases "
              "across Saudi Arabia, and Pakistan.")
    assert apply_brief(yemen, longer, "") == (1, 0)
    assert yemen.sentences[1:] == [longer]  # replaces the shorter sentence instead of repeating it

    yankees = make_story(headline="Yankees Bumble Through 'Really Rough Night' in Game 2 Loss",
                         sentences=["The Yankees committed four errors in a shocking display of postseason baseball, "
                                    "losing 5-2 to the Tampa Bay Rays in Game 2 of the American League Division Series."])
    yankees.evidence[0].excerpt = ("The Yankees committed four errors, including three in the first inning, among other "
                                   "miscues in a shocking display of postseason baseball, as New York lost 5-2.")
    assert apply_brief(yankees, "The Yankees committed four errors, including three in the first inning.", "") == (0, 0)


def test_brief_details_must_add_something():
    from agent_reach.daily.brief import _novel, apply_brief
    from tests.daily_fakes import make_story

    czar = ["President Trump has named national intelligence chief Jay Clayton as the new AI czar, leading a new "
            "federal AI task force.", "Clayton will coordinate government engagement with artificial intelligence."]
    story = make_story(headline="Trump Names National Intelligence Chief as New AI Czar", sentences=list(czar))
    story.evidence[0].excerpt = ("Trump said Clayton will lead the White House's new \"Super Intelligence Force,\" which "
                                 "will coordinate government engagement with artificial intelligence. Director of national "
                                 "intelligence Jay Clayton is the new White House AI czar, President Trump said on Sunday.")
    assert apply_brief(story, "The new AI task force will coordinate government engagement with artificial "
                              "intelligence.", "") == (0, 0)
    pentagon = ["The US Department of Defence is no longer using Anthropic's AI tools after labelling the company a "
                "'supply chain risk'."]
    assert not _novel("The US Department of Defence labelled Anthropic a 'supply chain risk' in February.",
                      ["Pentagon Stops Using Anthropic AI Tools", *pentagon])
    assert _novel("Clayton previously chaired the Securities and Exchange Commission.",
                  ["Trump Names National Intelligence Chief as New AI Czar", *czar])


def test_why_it_matters_must_be_a_consequence_not_a_restatement():
    from agent_reach.daily.brief import apply_brief, concrete_effect
    from tests.daily_fakes import make_story

    assert not concrete_effect("The move is to comply with the EU's AI Act.")
    assert not concrete_effect("The 39-year-old will bid an emotional farewell.")
    assert not concrete_effect("LIV Golf hopes to continue into 2027.")
    assert not concrete_effect("The move aims to curb fuel costs.")  # a purpose (third rc10 run)
    assert concrete_effect("The incident has prompted the US to offer assistance to Russia.")

    story = make_story(headline="OpenAI to Watermark ChatGPT Text in EU",
                       sentences=["OpenAI will start watermarking ChatGPT's text in the EU to comply with the AI Act."])
    story.evidence[0].excerpt = ("OpenAI will watermark ChatGPT and Codex text in the EU to comply with the AI Act. "
                                 "Editing can make the invisible marks harder to detect, it says.")
    assert apply_brief(story, "", "The move is to comply with the EU's AI Act.") == (0, 0)
    assert story.why_it_matters is None


# ---------------------------------------------------------------- source notes and settings
def test_reddit_health_note_names_the_subreddit_not_its_url():
    import asyncio

    import httpx

    from agent_reach.config import Settings
    from agent_reach.ingestion.social import RedditIngester
    from tests.daily_fakes import RealAsyncClient

    entries = "".join(f"<entry><title>Big news story {i} today</title><link href='https://www.reddit.com/r/news/{i}'/>"
                      f"<category term='news'/></entry>" for i in range(3))
    atom = f'<?xml version="1.0"?><feed xmlns="http://www.w3.org/2005/Atom">{entries}</feed>'.encode()

    def handler(req):
        if req.url.path.endswith(".json"):
            return httpx.Response(403)
        if "worldnews" in req.url.path or "technology" in req.url.path:
            return httpx.Response(429, headers={"Retry-After": "0"})
        return httpx.Response(200, content=atom)

    settings = Settings(reddit_subreddits=["news", "worldnews", "technology"], reddit_max_retries=0,
                        reddit_request_spacing_s=0.0, http_backoff_base_s=0.01)

    async def go():
        async with RealAsyncClient(transport=httpx.MockTransport(handler)) as client:
            return await RedditIngester(client, settings, asyncio.Semaphore(2)).run()

    items, stat = asyncio.run(go())
    assert stat.ok and items
    # one cause, every subreddit it hit: the note fits instead of being cut mid-URL
    assert "r/worldnews, r/technology: HTTPStatusError: HTTP 429" in stat.error and "https://" not in stat.error


def test_version_6_settings_replace_yahoo_finance():
    from agent_reach.daily.feeds import default_feeds
    from agent_reach.daily.prefs import PREFS_VERSION, DailyPrefs

    yahoo = "https://finance.yahoo.com/news/rssindex"
    prefs = DailyPrefs.model_validate({"prefs_version": 6, "feeds": [
        {"name": "Yahoo Finance", "url": yahoo, "category": "News", "enabled": False},
        {"name": "My Paper", "url": "https://paper.test/rss", "category": "News"}]})
    assert prefs.prefs_version == PREFS_VERSION == 11
    by_name = {f.name: f for f in prefs.feeds}
    assert "Yahoo Finance" not in by_name and not by_name["Bloomberg - Markets"].enabled and by_name["My Paper"].enabled
    assert yahoo not in {f.url for f in default_feeds()}


# ---------------------------------------------------------------- cloud runner
def test_cloud_runner_gives_the_daily_refresh_a_cpu_sized_budget():
    import re
    from pathlib import Path

    from agent_reach.daily.prefs import DailyPrefs

    text = (Path(__file__).resolve().parents[1] / ".github" / "workflows" / "cloud-runner.yml").read_text("utf-8")
    articles = int(re.search(r"daily_articles \|\| '(\d+)'", text).group(1))
    minutes = float(re.search(r'DAILY_MAX_RUN_MINUTES: "(\d+)"', text).group(1))
    job_timeout = int(re.search(r"timeout-minutes: (\d+)", text).group(1))
    prefs = DailyPrefs(max_items_for_llm=articles, max_run_minutes=minutes)  # within the settings' bounds
    assert prefs.max_items_for_llm < DailyPrefs().max_items_for_llm and minutes + 10 <= job_timeout
    assert "prefs.max_items_for_llm = int(os.environ[\"DAILY_ARTICLES\"])" in text
